"""init schema

Revision ID: 0b62a69b5da6
Revises: 
Create Date: 2026-04-25 01:38:08.496174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0b62a69b5da6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'supervisor', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('rtsp_url', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('online', 'offline', 'error', name='camerastatus'), nullable=False),
    sa.Column('fps_target', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('no_helmet', 'no_vest', 'no_gloves', 'no_boots', 'no_mask', 'unauthorized_zone', 'unsafe_material', 'other', name='violationtype'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', 'false_positive', name='violationstatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('snapshot_url', sa.String(length=500), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violations_camera_id'), 'violations', ['camera_id'], unique=False)
    op.create_index(op.f('ix_violations_detected_at'), 'violations', ['detected_at'], unique=False)
    op.create_index(op.f('ix_violations_severity'), 'violations', ['severity'], unique=False)
    op.create_index(op.f('ix_violations_status'), 'violations', ['status'], unique=False)
    op.create_index(op.f('ix_violations_type'), 'violations', ['type'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Enum('websocket', 'push', 'email', name='alertchannel'), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_violation_id'), 'alerts', ['violation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_violation_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_violations_type'), table_name='violations')
    op.drop_index(op.f('ix_violations_status'), table_name='violations')
    op.drop_index(op.f('ix_violations_severity'), table_name='violations')
    op.drop_index(op.f('ix_violations_detected_at'), table_name='violations')
    op.drop_index(op.f('ix_violations_camera_id'), table_name='violations')
    op.drop_table('violations')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sites')
    # ### end Alembic commands ###
