// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfa3QaQ_xQ5fVpkPOsOzrwHtJeopd3fDU',
    appId: '1:1053439862866:web:86c27b9b610386f3f2978b',
    messagingSenderId: '1053439862866',
    projectId: 'fyp-backend-fa22',
    authDomain: 'fyp-backend-fa22.firebaseapp.com',
    storageBucket: 'fyp-backend-fa22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxF0gmUn6kA3jsq4egf5OAIWOxQ7dPxS4',
    appId: '1:1053439862866:android:eab3f2b5c91995fcf2978b',
    messagingSenderId: '1053439862866',
    projectId: 'fyp-backend-fa22',
    storageBucket: 'fyp-backend-fa22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoMKHdkYhAKZoVFmcO3zU7-tepDQj-3x0',
    appId: '1:1053439862866:ios:a24c08211badd257f2978b',
    messagingSenderId: '1053439862866',
    projectId: 'fyp-backend-fa22',
    storageBucket: 'fyp-backend-fa22.firebasestorage.app',
    iosBundleId: 'com.devitcity.example',
  );

}