@echo off
echo Starting ML Backend API...
if not exist "venv" (
    echo Creating virtual environment...
    python -m venv venv
)
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Starting FastAPI server...
uvicorn main:app --host 0.0.0.0 --port 8001 --reload
pause
